language: php

php:
    - 7.0
    - 7.1

env:
  - COMPOSER_OPTIONS="--prefer-source"

before_script:
    - phpenv config-rm xdebug.ini
    - composer update $COMPOSER_OPTIONS

notifications:
  email: false
